FROM golang:1.10.2 as builder
WORKDIR /go/src/app
COPY . .
WORKDIR /go/src/app/client
RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o client .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/app/client/client .
ENV PULL_URL http://localhost:4502/metrics
ENV PROXY_URL http://contaner.proxy
CMD exec ./client --proxy-url=$PROXY_URL --pull-url=$PULL_URL